
#logging.level.com.tq=warn \u8BBE\u7F6E\u9ED8\u8BA4\u65E5\u5FD7\u7EA7\u522B\u8F93\u51FAwarn\u7EA7\u522B\u548C\u4E4B\u540E\u7684
#logging.file=springboot.log \u5F53\u524D\u9879\u76EE\u751F\u6210springboot.log\u65E5\u5FD7\u6587\u4EF6\uFF0C\u8FD8\u6709logging.path=...

#pop\u6388\u6743\u7801 huzpazqbotwzgfhe smtp\u6388\u6743\u7801yowrovyssdzoffgc
#spring.mail.username=1330875414@qq.com
#spring.mail.password=yowrovyssdzoffgc
#spring.mail.host=smtp.qq.com
#springboot1.x\u7248\u672C\u53D1\u9001\u90AE\u4EF6\u51FA\u9519\u53EF\u52A0 spring.mail.properties.mail.smtp.ssl.enable=true
spring:
  mail:
    username: 1330875414@qq.com
    password: yowrovyssdzoffgc
    host: smtp.qq.com
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081